# Generated by Django 6.0.7 on 2026-07-09 07:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='main_catego_name_5111b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='product/%Y/%m/%d')),
                ('description', models.TextField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to='main.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product/%Y/%m/%d')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.clothingitem')),
            ],
        ),
        migrations.CreateModel(
            name='ClothingItemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('clothing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clothingitem')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.size')),
            ],
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='clothing_item', through='main.ClothingItemSize', to='main.size'),
        ),
        migrations.AddConstraint(
            model_name='clothingitemsize',
            constraint=models.UniqueConstraint(fields=('clothing_item', 'size'), name='unique_clothingitem_size'),
        ),
        migrations.AlterUniqueTogether(
            name='clothingitemsize',
            unique_together={('clothing_item', 'size')},
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['price'], name='main_clothi_price_67d2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['slug'], name='main_clothi_slug_818b86_idx'),
        ),
        migrations.AddConstraint(
            model_name='clothingitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0), ('discount__lte', 100)), name='discount_between_0_and_100'),
        ),
    ]
