# Generated by Django 6.0.7 on 2026-07-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clothingitemsize',
            unique_together=set(),
        ),
    ]
