# Generated by Django 6.0.7 on 2026-07-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_clothingitemsize_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ['order']},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='main_catego_name_5111b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='clothingitem',
            name='main_clothi_slug_818b86_idx',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='product/%Y/%m/%d'),
        ),
    ]
